data_conf:
  test_list: data/test_list_5s.txt
  train_list: data/train_list_5s.txt
model_conf:
  asymmetric: false
  audio_mode: false
  force_no_residual: false
  in_channels: 3
  model_config:
  - - 1
    - 16
    - 1
    - 1
    - 0
  - - 6
    - 24
    - 2
    - 2
    - 2
  - - 6
    - 32
    - 3
    - 1
    - 0
  - - 6
    - 64
    - 4
    - 2
    - 2
  - - 6
    - 96
    - 3
    - 1
    - 0
  - - 6
    - 160
    - 3
    - 1
    - 0
  - - 6
    - 320
    - 1
    - 1
    - 0
  multiscale: false
  num_classes: 3
  width_mult: 1.0
train_conf:
  batch_size: 16
  freeze_backbone: false
  learning_rate: 0.001
  loss_conf:
    apply_logit_adj_in_eval: false
    apply_logit_adj_in_train: false
    gamma: 2.0
    label_smoothing: 0.1
    logit_adj_tau: 1.0
    loss_type: focal
    pair_penalty:
      targets:
      - - 1
        - 2
      - - 2
        - 0
      use_penalty: false
      weight: 2.0
  max_epoch: 50
  monitor_metric: f1
  num_workers: 4
  sampler_alpha: 0.5
  save_model_dir: saved_models/M4_MobileNetV2_CBAM
  seed: 42
  use_class_weights: false
  use_gpu: true
  use_sampler: false
  weight_decay: 0.0001
