data_conf:
  dataset_type: image
  image_size: 96
  test_dir: data/cifar10/test
  train_dir: data/cifar10/train
model_conf:
  in_channels: 3
  model_config:
  - - 1
    - 16
    - 1
    - 1
    - 0
  - - 6
    - 24
    - 2
    - 2
    - 2
  - - 6
    - 32
    - 3
    - 1
    - 0
  - - 6
    - 64
    - 4
    - 2
    - 2
  - - 6
    - 96
    - 3
    - 1
    - 0
  - - 6
    - 160
    - 3
    - 1
    - 0
  - - 6
    - 320
    - 1
    - 1
    - 0
  num_classes: 10
  width_mult: 1.0
train_conf:
  batch_size: 128
  learning_rate: 0.001
  max_epoch: 200
  num_workers: 4
  save_model_dir: saved_models/cifar10s_preDW_s24
  use_gpu: true
  weight_decay: 0.0005
