data_conf:
  train_list: 'data/train_list.txt'
  test_list: 'data/test_list.txt'



train_conf:
  batch_size: 4
  learning_rate: 0.001
  max_epoch: 1
  use_gpu: True
  num_workers: 0  # Avoid multiprocessing issues in test
  save_model_dir: 'saved_models/test/'
  weight_decay: 1.0e-4

model_conf:
  num_classes: 4
  width_mult: 1.0
  in_channels: 3
